import Head from 'next/head'
import { Layout } from '@/components/layout'
import { Erp360 } from '@/components/ERP360'


export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Layout title="ERP360">
        <Erp360 />
      </Layout>
    </>
  )
}
